// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RWA_Web_Api.Context;

#nullable disable

namespace RWA_Web_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("RWA_Web_Api.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("category_id")
                        .HasName("PRIMARY");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("first_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("last_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("customer_id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "user_id" }, "user_id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.FeaturedProduct", b =>
                {
                    b.Property<int>("featured_product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("algorithm")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.HasKey("featured_product_id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "product_id" }, "product_id");

                    b.ToTable("FeaturedProduct");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("order_date")
                        .HasColumnType("date");

                    b.Property<decimal?>("total_amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("order_id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "user_id" }, "user_id")
                        .HasDatabaseName("user_id1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("isNew")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("oldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("product_id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "category_id" }, "category_id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.UserAccount", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("user_id")
                        .HasName("PRIMARY");

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Customer", b =>
                {
                    b.HasOne("RWA_Web_Api.Models.UserAccount", "user")
                        .WithMany("Customers")
                        .HasForeignKey("user_id")
                        .HasConstraintName("customer_ibfk_1");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.FeaturedProduct", b =>
                {
                    b.HasOne("RWA_Web_Api.Models.Product", "product")
                        .WithMany("FeaturedProducts")
                        .HasForeignKey("product_id")
                        .HasConstraintName("featuredproduct_ibfk_1");

                    b.Navigation("product");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Order", b =>
                {
                    b.HasOne("RWA_Web_Api.Models.UserAccount", "user")
                        .WithMany("Orders")
                        .HasForeignKey("user_id")
                        .HasConstraintName("orders_ibfk_1");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Product", b =>
                {
                    b.HasOne("RWA_Web_Api.Models.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .HasConstraintName("product_ibfk_1");

                    b.Navigation("category");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.Product", b =>
                {
                    b.Navigation("FeaturedProducts");
                });

            modelBuilder.Entity("RWA_Web_Api.Models.UserAccount", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
